### ISSUE TITLE
After adding an altLabel, the vocabulary in SKOSMOS fails to load.

### ISSUE THREAD

**Issue by gulzaure** [kit-data-manager/EVOKS#228] opened 2024-10-22 11:21 UTC
After adding the alternative label property to the term, the vocabulary cannot be loaded in SKOSMOS. There is an error message: 'Top hierarchy cannot be loaded'.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by FelixFrizzy** [comment] 2024-10-22 11:38
I could not reproduce the problem, on my side it worked for a general term. Could you provide more details? E.g. a screenshot of the filled "adding property popup" and how the terms looks like after adding the altLabel property (and breaking skosmos) would be great!
You can also fill the template that I provided, that makes it a little easier to debug the problem.

**Comment by FelixFrizzy** [comment] 2024-10-24 08:56
Investigation showed that the problem was that the altLabel was set to URI which does not work. It has always to be string. Close this issue, broader context can be found in #229

**Closed as completed by FelixFrizzy** 2024-10-24 08:56 UTC
Labels: bug
